### ISSUE TITLE
突然没搞明白这个到底是微信机器人呢还是啥

### ISSUE THREAD

**Issue by lizhi2013** [agenthun/WeixinBot#2]
突然没搞明白这个到底是微信机器人呢还是啥，如果是微信机器人按理不需要扫码登陆，只要配置好
启动服务，把微信公众号指到这里不就可以了吗

**Comment by lizhi2013** [comment]
实际上是不知道为何 公众平台登陆之扫码验证

**Comment by agenthun** [comment]
是一个以个人身份登陆的微信机器人，扫码登陆后即作为机器人自动回复对方。有点区别于公众号，像是私人代理。确实这个方式有点怪，是当时参加一个黑客马拉松的题目

**Comment by agenthun** [comment]
扫码验证是接入用户数据，可能更好的方式是，在微信里提供开启代理的一个按钮，一按后就启动后台服务
